version: '3.4'

services:
  eshopwebmvc:
    image:  eshopacr.azurecr.io/eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
  eshoppublicapi:
    image:  eshopacr.azurecr.io/eshoppublicapi
    container_name: eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name:  eshopacr.azurecr.io/eshopsql
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

