# File: .github/workflows/workflow.yml

on: [workflow_dispatch]

name: Login to Azure US Government cloud

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        environment: 'AzureUSGovernment'
        enable-AzPSSession: true
    
