name: Docker Image CI

on:
  workflow_dispatch:
      inputs:
        version:
          type: string
          default: $(date +%s)
          required: true
  push:
    branches:
      - dev
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build 

    - name: Deploy to ARC
      uses: azure/docker-login@v1
      with:
            login-server: eshopacr.azurecr.io
            username: eshopacr
            password: o8uXSgWlUdRwAeGP2xGSfGy+09vetsONo3Mq13fksa+ACRBXyFsY
    - run: |
            docker push eshopacr.azurecr.io/eshopwebmvc
            docker push eshopacr.azurecr.io/eshoppublicapi
            docker push eshopacr.azurecr.io/eshopsql

      
      
      # --tag my-image-name:$(github.event.inputs.environment)
