name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build 

    - name: Deploy to ARC
      uses: azure/docker-login@v1
      with:
            login-server:  ${{ vars.ACR_SERVER }}
            username: ${{ vars.ACR_USERNAME }}
            password: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
            docker push eshopacr.azurecr.io/eshopwebmvc
            docker push eshopacr.azurecr.io/eshoppublicapi      
  
