name: KeyVault and Github

on:
  workflow_dispatch:

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

  
jobs:

  build:
    environment: Development   
    runs-on: ubuntu-latest

    steps:

    - name: Log into Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: 'alex-demo-kv'
        secrets: 'ACR-PASS'
      id: arc-pass
          
 


   
