name: eShopOnWeb Build and Test

# Triggers (uncomment line below to use it)
on: 
  workflow_dispatch

# Environment variables
env:
  RESOURCE_GROUP: rg-eshoponweb-westeurope
  LOCATION: westeurope
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 534f67f5-645c-45c4-825b-6e228e272a74
  WEBAPP_NAME: devops-webapp-westeurope-411724194

jobs:
  # Build, test, and publish .NET web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      
      # Prepare runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'
      
      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release
      
      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release
      
      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .
      
      # Upload the published website code artifacts
      - name: Upload .NET app artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      # Upload the Bicep template as an artifact for the next job
      - name: Upload Bicep template artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

  # Use Bicep to deploy infrastructure + publish web app
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download the published files created in the previous job
      - name: Download .NET app artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./dotnet-app

      # Download the Bicep template from the previous job
      - name: Download Bicep template artifact
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: ./bicep-template

      # Login to Azure subscription using a service principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using the Bicep file
      - name: Deploy Azure WebApp using Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./bicep-template/webapp.bicep
          parameters: |
            webAppName=${{ env.WEBAPP_NAME }}
            location=${{ env.LOCATION }}
          failOnStdErr: false

      # Publish website to Azure App Service using Azure CLI
      - name: Publish Website to WebApp
        uses: azure/cli@v2
        with:
          azcliversion: latest
          scriptType: bash
          inlineScript: |
            az webapp deploy --resource-group ${{ env.RESOURCE_GROUP }} \
                             --name ${{ env.WEBAPP_NAME }} \
                             --src-path ./dotnet-app/app.zip \
                             --type zip

        inlineScript: |
             az webapp deploy --name ${{ env.WEBAPP-NAME }} --resource-group ${{ env.RESOURCE-GROUP }} --src-path .net-app/app.zip --type zip
